# Generated by Django 5.1.3 on 2024-12-12 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustonUser',
            new_name='CustomUser',
        ),
    ]
